### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by neouks** [virusmore/virusmore#1]
有点鸡肋了，现在用basic和digest的网站并不是很多，而且这样也没有burp方便。
将繁琐复杂的事情自动化才是好的工具，希望作者再接再厉。

**Comment by virusmore** [comment]
我们本就没打算用于web的破解啊，另有他用，只是如文中所言，在cli环境下进行低功耗的在线攻击，具体用户后面会有文章说明

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 沙洲思念谁 ***@***.***>
发送时间: Monday, June 28, 2021 9:38:21 AM
收件人: virusmore/virusmore ***@***.***>
抄送: Subscribed ***@***.***>
主题: [virusmore/virusmore] 建议 (#1)


有点鸡肋了，现在用basic和digest的网站并不是很多，而且这样也没有burp方便。
将繁琐复杂的事情自动化才是好的工具，希望作者再接再厉。

―
